name: midleapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Use 'any' para deixar o FlutLab escolher as melhores versões compatíveis
  firebase_core: any
  firebase_auth: any
  cloud_firestore: any
  url_launcher: any # Adicionando a dependência que criei para você
  cupertino_icons: ^1.0.2 # Versão padrão

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true