// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEjJ_MCKFvDeMg8kPGUXIwi1EQgqq6x_o',
    appId: '1:907465739229:web:d726d74be95ddb07388434',
    messagingSenderId: '907465739229',
    projectId: 'mindleapp-9d40f',
    authDomain: 'mindleapp-9d40f.firebaseapp.com',
    storageBucket: 'mindleapp-9d40f.firebasestorage.app',
    measurementId: 'G-9K9GY08W3L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSXbfZm-Rv3tv8nlJEg0Q1PwaKzsk4zH8',
    appId: '1:907465739229:android:2b2b4495497cea1e388434',
    messagingSenderId: '907465739229',
    projectId: 'mindleapp-9d40f',
    storageBucket: 'mindleapp-9d40f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPabAe9YYMQMU0V6988xKA-yOfya43DxA',
    appId: '1:907465739229:ios:7a594e853d05f2ef388434',
    messagingSenderId: '907465739229',
    projectId: 'mindleapp-9d40f',
    storageBucket: 'mindleapp-9d40f.firebasestorage.app',
    iosBundleId: 'com.example.midleapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPabAe9YYMQMU0V6988xKA-yOfya43DxA',
    appId: '1:907465739229:ios:7a594e853d05f2ef388434',
    messagingSenderId: '907465739229',
    projectId: 'mindleapp-9d40f',
    storageBucket: 'mindleapp-9d40f.firebasestorage.app',
    iosBundleId: 'com.example.midleapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEjJ_MCKFvDeMg8kPGUXIwi1EQgqq6x_o',
    appId: '1:907465739229:web:c335712817a313c9388434',
    messagingSenderId: '907465739229',
    projectId: 'mindleapp-9d40f',
    authDomain: 'mindleapp-9d40f.firebaseapp.com',
    storageBucket: 'mindleapp-9d40f.firebasestorage.app',
    measurementId: 'G-76YBV50XRD',
  );
}
